version: v2

tasks:
  spec:
    containers:
      - image: centos
    steps:
      - checkout
      - commands:
        - env
        - echo test
    # Note. RazorOps branch is not include directory
    # e.g. feature/test -> test
    when: (branch in ('master', 'develop') || branch =~ 'razorops.*') && event == 'pull_request'
