version: v2

tasks:
  spec:
    containers:
      - image: centos
    steps:
      - checkout
      - commands:
        - env
        - echo test
    when: (branch in ('master', 'develop') || branch =~ 'razorops.*')
