tasks:
  test:
    image: centos
    commands:
      - echo test
    # Note. RazorOps branch is not include directory
    # e.g. feature/test -> test
    when: >
      branch in ('master', 'develop') ||
      branch =~ 'razorops.*'
