tasks:
  test:
    # image: gcc
    image: srzzumix/gcc3:centos5
    commands:
      - echo test
    # Note. RazorOps branch is not include directory
    # e.g. feature/test -> test
    when: >
      branch in ('master', 'develop') ||
      branch =~ 'razorops.*'
