dist: trusty
sudo: false

language: cpp

branches:
  except:
    - gh-pages
  only:
    - master
    - develop
    - /feature.*/
    - /fix.*/
    - /travisci.*/
    - /travis-ci.*/

script:
  - echo OK

notifications:
  email: false
