version: 1.0.{build}
branches:
  only:
    - master
    - develop
    - /appveyor\/.*/

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

build_script:
  - cmd: echo OK
test: off
skip_commits:
  message: /\[no appveyor\]/
