resources:
  - name: ci_trigger_gitRepo
    type: GitRepo
    configuration:
      gitProvider: GitHub
      path: srz-zumix/ci-trigger
      branches:
        include: master|^feature/.*|^jfrog/.*
pipelines:
  - name: ci_trigger
    steps:
      - name: spec
        type: Bash
        configuration:
          inputResources:
            - name: ci_trigger_gitRepo
        execution:
          onStart:
          - update_commit_status ci_trigger_gitRepo # Status: "processing"
          onExecute:
            - update_commit_status ci_trigger_gitRepo # Status: "processing"
            - pushd ${res_ci_trigger_gitRepo_resourcePath}
            - echo OK
            - popd
          onFailure:
            - update_commit_status ci_trigger_gitRepo # Status: "failure"
          onSuccess:
            - update_commit_status ci_trigger_gitRepo # Status: "success"
