version: 2.1
parameters:
  build-docs:
    type: boolean
    default: false
  build-pipeline:
    type: boolean
    default: false
  build-other:
    type: boolean
    default: false

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:cosmic-browsers
    steps:
      - checkout
      - run:
          name: Greeting
          command: |
            echo  Hello, world 1.
            echo "build-docs is << pipeline.parameters.build-docs >>"
            echo "build-pipeline is << pipeline.parameters.build-pipeline >>"
            <<# pipeline.parameters.build-pipeline >> echo PIPELINE <</ pipeline.parameters.build-pipeline >>
            <<# pipeline.parameters.build-docs >> echo README <</ pipeline.parameters.build-docs >>
      - when:
          condition:
            when: << pipeline.parameters.build-docs >>
          steps:
            - run: echo build-docs
      - when:
          condition:
            when: << pipeline.parameters.build-pipeline >>
          steps:
            - run: echo build-pipeline

workflows:
  build-docs:
    when: << pipeline.parameters.build-docs >>
    jobs:
      - build
  build-pipeline:
    when: << pipeline.parameters.build-pipeline >>
    jobs:
      - build
  build-other:
    when: << pipeline.parameters.build-other >>
    jobs:
      - build
